import React from 'react';
import Head from 'next/head';
import ContactEmp from '../../components/ContactEmp';

function empangeni() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Contact Us</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>
			<ContactEmp />
		</div>
	);
}

export default empangeni;
