import React from 'react';
import Head from 'next/head';
import Projects from '@/components/Projects';

function projects() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Projects</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>

			<Projects />
		</div>
	);
}

export default projects;
