import React from 'react';
import Head from 'next/head';
import LBProjects from '@/components/LBProjects';

function laminatedbeams() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Laminated Beams</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>

			<LBProjects />
		</div>
	);
}

export default laminatedbeams;
