import React from 'react';
import Head from 'next/head';
import SteelProjects from '@/components/SteelProjects';

function lgsteel() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Light Gauge Steel</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>

			<SteelProjects />
		</div>
	);
}

export default lgsteel;
