import React from 'react';
import Head from 'next/head';
import TimberProjects from '@/components/TimberProjects';

function projects() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Timber</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>

			<TimberProjects />
		</div>
	);
}

export default projects;
