import React from 'react';
import Footer from '@/components/Footer';
import Head from 'next/head';
import Contact from '@/components/Contact';
import Copyright from '@/components/Copyright';

function contact() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Contact Us</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>
			<Contact />
		</div>
	);
}

export default contact;
