import React from 'react';
import Head from 'next/head';
import Landing from '../components/Landing';
import ActionBar from '../components/ActionBar';
import About from '../components/About';
import ActionBtn from '../components/ActionBtn';
import ProjectSlider from '../components/ProjectSlider';
import Footer from '@/components/Footer';
import Copyright from '@/components/Copyright';

export default function Home() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>
			<div>
				<section className='absolute z-20 mt-[15%] ml-64 text-[70pt] font-ttHoves text-white'>
					We can build your
					<div className='text-8xl text-left font-loveloLine'>DREAM</div>
					<div className='mt-20 text-[25pt] w-[25rem] font-belleza text-white'>
						Let us help you make your dream home a reality
					</div>
					<ul>
						<button>
							<li className='yellowButton absolute -mt-16 font-openSans tracking-wider font-semibold text-[14pt]'>
								Get in touch
							</li>
						</button>
					</ul>
				</section>
				<Landing />
				<ActionBar />
				<About />
				<ActionBtn />
				<ProjectSlider />
				<Footer />
				<Copyright />
			</div>
		</div>
	);
}
