import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Landing from '../components/Landing';
import ActionBar from '../components/ActionBar';
import About from '../components/About';
import ActionBtn from '../components/ActionBtn';
import ProjectSlider from '../components/ProjectSlider';

export default function Home() {
	return (
		<div className='scroll-smooth bg-[#292929]'>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/images/bbsIcon.png' />
			</Head>
			<div>
				<section className='absolute z-20 mt-[15%] lg:mt-[12%] ml-12 md:ml-24 lg:ml-36 2xl:ml-64 text-5xl xl:text-[70pt] font-ttHoves text-white'>
					We can build your
					<div className='xl:text-8xl text-6xl mt-4 2xl:mt-8 text-left font-loveloLine'>
						DREAM
					</div>
					<div className='2xl:mt-20 mt-10 text-[20pt] xl:text-[25pt] w-[25rem] font-belleza text-white'>
						Let us help you make your dream home a reality
					</div>
					<ul>
						<Link href='/contact'>
							<button>
								<li className='yellowButton absolute md:-mt-18 lg:-mt-12 2xl:mt-0 font-openSans tracking-wider font-semibold text-[14pt]'>
									Get in touch
								</li>
							</button>
						</Link>
					</ul>
				</section>
				<Landing />
				<ActionBar />
				<About />
				<ActionBtn />
				<ProjectSlider />
			</div>
		</div>
	);
}
